### PR TITLE
Update typography, VR, and basic responsive breakpoints

### PR DESCRIPTION
**Pull request by phuedx**
joakin-loot-ui-pr-18
## TODO
- [x] Typography and vertical rhythm
- [x] Basic responsive breakpoints
- [x] Infobox styles for low-width devices
- [x] Deal with inline styles of infoboxes that are not mobile friendly (like `float: right` on [The Last of Us](http://reading-web-research.wmflabs.org/wiki/The%20Last%20of%20Us))

### CODE REVIEW

**Comment by joakin** [comment]
Holy shit it looks like mobilefrontend! :+1:

**Comment by joakin** [comment]
Regarding the f**king infobox from hell, that one you're seeing not behave is because it has a nice and awesome `float:right` inline style that overrides the mobile first styles from `section.less`. 

Right now info's are centered in mobile, and when bigger than tablet (768) they become float right.  This means that either we strip that in the parser, or we cssoverride it here with our other two friends so that it is mobile first https://github.com/joakin/loot-ui/blob/master/lib/client/components/section/section.less#L35-L36 with a `float: none !important`. What do you think?

**Comment by joakin** [comment]
Also with this font size too little content actually remains on the left of the infobox at 768px, so if you want we can change [`.larger-than-tablet`](https://github.com/joakin/loot-ui/blob/master/lib/client/components/section/section.less#L37-L41) to `.larger-than-desktop` so that it looks better:

This is currently on a non-evil infobox:

responsiveface-sm

This is changing [`.larger-than-tablet`](https://github.com/joakin/loot-ui/blob/master/lib/client/components/section/section.less#L37-L41) to `.larger-than-desktop`:

responsiveface-lgdesktop-sm

**Comment by joakin** [comment]
Which brings us to a last issue, something is wrong between portrait tablet and desktop:

mf-lui-differences

**Comment by joakin** [comment]
I've marked  _Infobox styles for low-width devices_ as done, because that was already there and added _Deal with inline styles of infoboxes that are not mobile friendly (like float: right on The Last of Us)_ as a todo item.

**Comment by joakin** [comment]
BTW ping me to meet in person if unclear, I feel like I'm blasting comments around and making things confusing... sorry. I'll stop now.

**Comment by phuedx** [comment]
I forgot to say that [the change you suggested above](https://github.com/joakin/loot-ui/pull/18#issuecomment-160271008) also fixes [the last bug you spotted](https://github.com/joakin/loot-ui/pull/18#issuecomment-160271636).

**Comment by joakin** [comment]
@phuedx In this last commit I've fixed the infobox setting with a `style` attribute a float that breaks the infobox on mobile layouts.

Have a look and see if it's acceptable. Otherwise just rewind head and force push to this branch to get rid of it.

**Comment by phuedx** [comment]
👍

**Pull request merged**
