### PR TITLE
Document loot-ui

### PR DESCRIPTION
**Pull request by joakin**
- [x] Set up gitbook for the docs
- [x] Document

### CODE REVIEW

**Comment by joakin** [comment]
I've pre-published them to see if the publish command worked properly http://chimeces.com/loot-ui/

For now this looks good to me as project docs @phuedx, will expand as we come across more stuff.

I'll address code docs in some other PR, and see how we can publish those too (if necessary). (and tests btw...).

Looking forward to review. Feel free to add commits to the PR and ping me if you correct wording/grammar.

**Comment by phuedx** [comment]
> (and tests btw...). </snip>

Something on your mind, @joakin? 😜

**Comment by joakin** [comment]
Regarding tests? What do you mean :stuck_out_tongue: 

We're not testing at all :sob:

**Pull request merged**
