### PR TITLE
Add LastModifiedBar

### PR DESCRIPTION
**Pull request by jdlrobson**
Do the bare minimum that is legally required - link to article
history page on English Wikipedia (existing mobile)

Add support for 'Last edited by Username' (username linking to
Special:Userprofile) - this is currently not wired up. In future
we could load this on scroll - in most cases it's not actually necessary
just being an enhancement.

Changes:
- Add truncated text mixin

Fixes: #29

### CODE REVIEW

**Comment by joakin** [comment]
Going to review. Can you please rebase on master and `push --force`?  I don't want to do it becaues I don't know if you have in progress work and I don't want to fuck git up. (There's CI now running on PRs after you rebase).

**Comment by joakin** [comment]
Note that when you push force the comments may disappear, we'll see.

**Comment by joakin** [comment]
Regarding 3c8d013:

I think sending the last modified information as part of the article API would make more sense. We avoid extra round trips, and costly scroll binding.

Right now the API sends this:

``` json
{
  "sections": [
    {...}
    ...
  ]
}
```

It would be nice to add the aggregation on `loot` and make the `/api/slim/:title` return the last modified information too:

``` json
{
  "lastModified": {
    "date": 123456789,
    "author": "Jon"
  },
  "sections": [
    {...}
    ...
  ]
}
```

We would then just consume that from the component and render it.

That's why we have an aggregation service right? So that we can pack together information and avoid other round trips.

**Comment by joakin** [comment]
I've checked restbase's output and it seems like this properties are already in the HTML document, we're just not returning them (See the `<head>`):

``` html
<meta property="mw:TimeUuid" content="308dda3d-a102-11e5-94d7-00677141a714"/><meta property="mw:articleNamespace" content="0"/>
<link rel="dc:replaces" resource="mwr:revision/693155720"/>
<meta property="dc:modified" content="2015-12-06T16:14:29.000Z"/>
<meta about="mwr:user/0" property="dc:title" content="99.231.104.35"/>
<link rel="dc:contributor" resource="mwr:user/0"/>
<meta property="mw:revisionSHA1" content="02409a9674cbee7c4c69b3e0b2615cc30ea1bcba"/>
<meta property="dc:description" content='/* Notable residents */Removed the word "famous" and replaced with neutral word "notable." Also changed "citizens" to "residents."'/>
<meta property="mw:parsoidVersion" content="0"/>
<link rel="dc:isVersionOf" href="//en.wikipedia.org/wiki/Alicante"/>
```

See more concretely this 3 tags:

``` html
<meta property="dc:modified" content="2015-12-06T16:14:29.000Z"/>
<meta about="mwr:user/0" property="dc:title" content="99.231.104.35"/>
<link rel="dc:contributor" resource="mwr:user/0"/>
```

Those have all the info, so we wouldn't need to do additional requests in loot.

**Comment by joakin** [comment]
Does the approach make sense?
1. Add last modified info to loot response
2. Just render it on the client instead of  3c8d013

**Comment by jdlrobson** [comment]
Mmm yeh sending in I've pushed a bunch of changes. There's still open concerns in my head around the Class vs function thing but that aside I think this is good enough to merge.

**Comment by joakin** [comment]
Looks nice. I'm going to take the liberty of making it a stateless component (which it already is). We can video chat about that to clear it out!

**Comment by joakin** [comment]
Thanks a lot!

I've applied a couple of changes when merging:
- Extract mobile enwiki URL to constant: ea8f317
- Transform last-modified to a stateless component 3951cd5

**Comment by joakin** [comment]
As you mentioned on the commit this makes more noticeable that we're not cache invalidating things right now, but it is something we'll get to, don't worry.

About i18n, it is definitely an important topic to think about, but there are plenty of solutions, so we'll get to that eventually too. 
For example this is how khan academy does it https://github.com/Khan/react-components/blob/master/js/i18n.jsx We could have something similar adapted to our translation systems.

**Comment by joakin** [comment]
Basically any JS i18n library could also work.

I've deployed the changes `\o/` http://reading-web-research.wmflabs.org/wiki/Wikipedia

**Pull request merged**
